// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPet.DataAccess;

namespace MyPet.DataAccess.Migrations
{
    [DbContext(typeof(PetDbContext))]
    partial class PetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyPet.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressNo = "07",
                            City = "Polgahawela",
                            FullName = "Chathumini Dasanayake",
                            PhoneNumber = "0712400284",
                            Street = "Wela"
                        },
                        new
                        {
                            Id = 2,
                            AddressNo = "08",
                            City = "Polgahawela",
                            FullName = "Nadeesh Fernando",
                            PhoneNumber = "0774964200",
                            Street = "Wela"
                        },
                        new
                        {
                            Id = 3,
                            AddressNo = "09",
                            City = "Polgahawela",
                            FullName = "Chandrakeerthi Dasanayake",
                            PhoneNumber = "0718070325",
                            Street = "Wela"
                        },
                        new
                        {
                            Id = 4,
                            AddressNo = "10",
                            City = "Polgahawela",
                            FullName = "Nilanthi Adikari",
                            PhoneNumber = "0718195376",
                            Street = "Wela"
                        },
                        new
                        {
                            Id = 5,
                            AddressNo = "11",
                            City = "Polgahawela",
                            FullName = "Anjana Dasanayake",
                            PhoneNumber = "0713620646",
                            Street = "Wela"
                        });
                });

            modelBuilder.Entity("MyPet.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Catogery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catogery = "Dog(DB)",
                            Color = "Black & White",
                            Date = new DateTime(2024, 7, 14, 17, 42, 21, 84, DateTimeKind.Local).AddTicks(4620),
                            Gender = 0,
                            Name = "Blacky",
                            OwnerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Catogery = "Dog",
                            Color = "Brown",
                            Date = new DateTime(2024, 7, 14, 17, 42, 21, 85, DateTimeKind.Local).AddTicks(9695),
                            Gender = 1,
                            Name = "Chooty",
                            OwnerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Catogery = "Dog",
                            Color = "Brown and White",
                            Date = new DateTime(2024, 7, 14, 17, 42, 21, 85, DateTimeKind.Local).AddTicks(9718),
                            Gender = 1,
                            Name = "Kelly",
                            OwnerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Catogery = "Dog",
                            Color = "Black",
                            Date = new DateTime(2024, 7, 14, 17, 42, 21, 85, DateTimeKind.Local).AddTicks(9722),
                            Gender = 1,
                            Name = "Kikki",
                            OwnerId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Catogery = "Cat",
                            Color = "Ash",
                            Date = new DateTime(2024, 7, 14, 17, 42, 21, 85, DateTimeKind.Local).AddTicks(9724),
                            Gender = 1,
                            Name = "Kitty",
                            OwnerId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Catogery = "Dog",
                            Color = "Black",
                            Date = new DateTime(2024, 7, 14, 17, 42, 21, 85, DateTimeKind.Local).AddTicks(9726),
                            Gender = 0,
                            Name = "Teena",
                            OwnerId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("MyPet.Models.Pet", b =>
                {
                    b.HasOne("MyPet.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyPet.Models.Owner", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
